"use client";

import { ArrowRight } from "lucide-react";

import { PaperSetupStage, SubjectSelectionStage, TopicsStage } from "@/app/_components/paper-maker/paper-maker-stages";
import { usePaperMakerWorkspace, type PaperMakerWorkspaceProps } from "@/app/_components/paper-maker/paper-maker-workspace-controller";
import { BuilderProgress } from "@/app/_components/paper-maker/builder-progress";
import { GenerationState } from "@/app/_components/paper-maker/generation-state";
import { PaperAssemblyModal } from "@/app/_components/paper-maker/paper-assembly-modal";
import { SubjectEmboss } from "@/app/_components/paper-maker/subject-emboss";

export function PaperMakerWorkspace(props: PaperMakerWorkspaceProps) {
  const workspace = usePaperMakerWorkspace(props);
  const { activeSubject, activeTier, selectedSubjectKey, builderStage, stageDirection, stageHeadingRef, groupedSubjectOptions, activeBoardGroup, hasChosenSubject, topicsReady, topicSelectionEnabled, canGenerate, result, router } = workspace;

  return <div className="pb-24 lg:pb-0">
    <header className="mx-auto max-w-[1240px] pb-5"><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end"><div><h1 className="text-[clamp(1.85rem,3vw,2.55rem)] font-bold leading-tight tracking-[-0.05em] text-text">Build a practice paper</h1><p className="mt-1.5 max-w-[58ch] text-[0.8rem] leading-5 text-text-muted">Choose your course and topics, then set the paper length.</p></div><div className="lg:justify-self-end"><BuilderProgress stage={builderStage} subjectReady={hasChosenSubject} topicsReady={topicsReady} topicSelectionEnabled={topicSelectionEnabled} onStageChange={workspace.goToStage} /></div></div></header>
    <div className={`mx-auto mt-5 ${builderStage === "subject" ? "max-w-[1240px]" : "max-w-[1180px]"}`}><div key={builderStage} data-builder-stage={builderStage} data-direction={stageDirection} className="builder-stage-enter">
      {builderStage === "subject" ? <SubjectSelectionStage groups={groupedSubjectOptions} activeBoardLabel={activeBoardGroup?.boardLabel ?? ""} headingRef={stageHeadingRef} onBoardChange={workspace.setActiveBoardLabel} onSubjectChange={workspace.handleSubjectChange} /> : <div className="space-y-6">
        <section className="grid gap-4 border-b border-text/12 pb-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center" aria-labelledby="course-heading"><div className="flex min-w-0 items-center gap-3"><SubjectEmboss subjectKey={selectedSubjectKey} surface="#F5F1E8" size={50} /><div className="min-w-0"><h2 id="course-heading" className="truncate text-[1.08rem] font-semibold tracking-[-0.035em] text-text">{activeSubject?.label ?? "Choose a course"}</h2>{activeTier ? <p className="mt-0.5 text-[0.68rem] font-medium text-text-muted">{activeTier.label}</p> : null}</div></div><div className="grid w-full grid-cols-1 items-center gap-2 sm:flex sm:w-auto sm:justify-end sm:gap-3">{activeSubject?.tiers.length ? <div className="flex w-full overflow-hidden rounded-[4px] border border-text/12 bg-white sm:w-auto">{activeSubject.tiers.map((tier) => <button key={tier.key} type="button" onClick={() => workspace.handleTierChange(tier.key)} className={`btn-press w-1/2 border-r border-text/12 px-3 py-2 text-[0.7rem] font-semibold last:border-r-0 sm:w-auto ${workspace.selectedTier === tier.key ? "bg-accent text-white" : "text-text-muted hover:text-accent"}`}>{tier.label}</button>)}</div> : null}<button type="button" onClick={() => workspace.goToStage("subject")} className="btn-press inline-flex min-h-10 w-full items-center justify-center gap-2 whitespace-nowrap rounded-[4px] border border-text/15 bg-white px-4 text-[0.7rem] font-semibold text-text-secondary hover:border-accent hover:text-accent sm:w-auto">Change course<ArrowRight className="h-3.5 w-3.5" /></button></div></section>
        {workspace.subjectDetailError ? <div className="border border-danger/20 bg-danger-soft px-4 py-4" role="alert"><p className="text-[0.78rem] font-semibold text-danger">We could not load {activeSubject?.label}.</p><p className="mt-1 text-[0.74rem] leading-5 text-danger/80">{workspace.subjectDetailError}</p><button type="button" onClick={() => activeSubject && workspace.loadSubjectDetail(activeSubject.key)} className="btn-press mt-3 border border-danger/30 bg-danger px-3 py-2 text-[0.72rem] font-semibold text-white">Try loading again</button></div> : null}
        {builderStage === "topics" && workspace.activeSubject ? <TopicsStage activeSubjectLabel={activeSubject.label} headingRef={stageHeadingRef} topicSearch={workspace.topicSearch} filteredTopics={workspace.filteredTopics} activeTopicGroup={workspace.activeTopicGroup} expandedIds={workspace.expandedIds} selectedLeafIds={workspace.selectedLeafIds} selectedTopicSummaries={workspace.selectedTopicSummaries} isLoading={workspace.isLoadingSubjectDetail} detailLoaded={activeSubject.detailLoaded} topicsReady={topicsReady} onSearchChange={workspace.setTopicSearch} onClearSearch={() => workspace.setTopicSearch("")} onActiveGroupChange={workspace.setActiveTopicGroupId} onToggleExpanded={workspace.toggleExpanded} onToggleSelected={workspace.toggleSelected} onRemoveTopic={workspace.removeTopic} onClearTopics={workspace.clearTopics} onContinue={() => workspace.goToStage("paper")} /> : null}
        {builderStage === "paper" && activeSubject ? <PaperSetupStage subjectKey={selectedSubjectKey} subjectLabel={activeSubject.label} activeTierLabel={activeTier?.label} headingRef={stageHeadingRef} topicSelectionEnabled={topicSelectionEnabled} selectedTopicSummaries={workspace.selectedTopicSummaries} targetMarks={workspace.targetMarks} timeMinutes={workspace.timeMinutes} questionMix={workspace.questionMix} paperCount={workspace.paperCount} generationEnabled={workspace.generationEnabled} activeMinutesPerMark={workspace.activeMinutesPerMark} activePaperOptions={workspace.activePaperOptions} resolvedPaperCodes={workspace.resolvedPaperCodes} paperSourcesCustomized={workspace.paperSourcesCustomized} canGenerate={canGenerate} isAuthenticated={workspace.isAuthenticated} error={workspace.error} isPending={workspace.isPending} generationMode={workspace.generationMode} onBackToTopics={() => workspace.goToStage("topics")} onMarksChange={workspace.updateFromMarks} onTimeChange={workspace.updateFromTime} onQuestionMixChange={workspace.setQuestionMix} onPaperCodeToggle={workspace.togglePaperCode} onSelectAllPapers={() => { workspace.setPaperSourcesCustomized(true); workspace.setSelectedPaperCodes(new Set(workspace.activePaperOptions.map((paper) => paper.code))); }} onClearPapers={() => { workspace.setPaperSourcesCustomized(true); workspace.setSelectedPaperCodes(new Set()); }} onResetPapers={() => workspace.setPaperSourcesCustomized(false)} onPaperCountChange={workspace.setPaperCount} onGenerate={workspace.handleGenerate} /> : null}
      </div>}
    </div></div>
    {builderStage !== "subject" ? <div className="fixed inset-x-0 bottom-0 z-40 border-t border-text/10 bg-bg-elevated/95 p-3 lg:hidden">{builderStage === "topics" ? <button type="button" onClick={() => workspace.goToStage("paper")} disabled={!topicsReady} className="btn-press flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-accent px-5 text-[0.8rem] font-bold text-white disabled:opacity-40">Continue to paper setup<ArrowRight className="h-4 w-4" /></button> : <GenerationState canGenerate={canGenerate} isPending={workspace.isPending} generationMode={workspace.generationMode} paperCount={workspace.paperCount} compact onGenerate={workspace.handleGenerate} />}</div> : null}
    {workspace.isPending && workspace.generationMode ? <PaperAssemblyModal includeMarkScheme={workspace.generationMode === "paper-and-mark-scheme"} paperCount={workspace.paperCount} subjectKey={selectedSubjectKey} subjectLabel={activeSubject?.label ?? "exam"} /> : null}
    {result ? <workspace.SuccessModal result={result} subjectKey={selectedSubjectKey} subjectTier={activeSubject?.tiers.length ? workspace.selectedTier : undefined} subjectLabel={activeSubject?.label ?? ""} tierLabel={activeTier?.label} minutesPerMark={workspace.activeMinutesPerMark} isAuthenticated={workspace.isAuthenticated} onOpenMarking={async () => { if (!workspace.isAuthenticated) { router.push("/auth?redirect=/marking"); return; } if (result.savedPaperIds.length !== 1) { router.push("/marking"); return; } const payload = await workspace.createMarkingSubmission({ savedPaperId: result.savedPaperIds[0] }); router.push(`/marking/${payload.submissionId}`); }} onClose={() => workspace.setResult(null)} onBuildAnother={() => { workspace.setResult(null); workspace.setSelectedLeafIds(new Set()); }} /> : null}
  </div>;
}
